import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

# Polilla real en arte ASCII
ascii_moth = [
    "                                                                                                                                                                                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                ????J5GGB#BBP5YJ                                                ",
    "                                                                                                                                                                                                                                                                                                                                           ?Y5PGPGBB######BGPPPPJ                                               ",
    "                                                                                                                                                                                                                                                                                                                                         5GB##BBBB#######BGGGPGGPJ                                              ",
    "                                                                                                                                                                                                                                                                                                                                       55GBBBBGGPG#######BGGBBGGGP                                              ",
    "                                                                                                                                                                                                                                                                                                                                     5PPGBBBBBPBB#####B#BBGGGP55YJ                                              ",
    "                                                                                                                                                                                                                                                                                                                               YYYY5PPGGBBB##BBBB####BGGBG5P55PP                                                ",
    "                                                                                                                                                                                                                                                                                                                         JYPGPY5P5PPPPGGBBB#BGGBB####BPPPG5PGPPGG                                               ",
    "                                         PBB#####BBGGP5PPP5YJ??77777                                                                                                                                                                                                                                                 ?Y5PPPPPP555PPP5PGBBBBBBBPGB#####GGG5PPGBGPG                                               ",
    "                                      JPPPGGB#########BBBB###BG5YYJ??7                                                                                                                                                          ??????J                                                                           ??Y5YJYPGGBBBGP55PPPPPPGGGGBBBBB######BGGPGPGGGPG                                             ",
    "                                     JPBGGGBBB########BBGGB####BGBBGPP5JJ                                                                                                                                                     ?YYJ    ???                                                                     JY5PGGP5P55PBBBG5YYYPPPPPGBBBBB#########BPP5G5P55P                                                ",
    "                                     JGBBBBBBGB##########BGB###BBBGPPPP5P5YYYJ??                                                                                                                                             Y5J?      ??                                                                  JYPPGGPPP5GGGGPPBG5JJY5PGBBBBBBBBB####BBB#G555PPPP55                                                 ",
    "                                      JPGGPPGGPB##B#####BBGPB#BBBGGGP55555PPBGP5YJ??                                                                                                                                       5Y?7?                                                                        JJJJYPPPP55PGGPGGPGBGY55PGGGGBBBBBB#####BBBBBGPP55PPGB                                                  ",
    "                                        PGP5PG5GBGGG###BBGGPGBBGGGGPPP555P55PPPPPGP5Y                                                                                                                                      JPJ                                                                         YPGPYJY5P555PP555PGBGGGG5YY5PPGGGGGBBB#####GGBBBGGPPPGPG                                                 ",
    "                                         PPGGGPPPGPG######BGB##BBGGGGPPPPP555PGBBGGG5JJ5YJ                                                                                                                               YP?                                                                        5GGBBBG55P5PPPPPPPPPPPGP5PJJJY5PGBBB########BBBBGBGPP5PP5G5                                                 ",
    "                                           BGGPPPGB#############BBBGGGPGP5YY5PGGGP5555PPPPP5Y                                                77????????                                                                 5P?                                                                      55J5PPBBBGPPPPPPPPP5555555P55PYJYPGBB###########BPGBBBBP555GP5P55                                              ",
    "                                         GPPGGPBPPGG#########BBBBBBBBBGGPPP55PBG5PGPP55PPGGPPYJJ                                          ???7       ???7JJ                                                           75P?                                                                    YYY55PGGGPPGGGG5PGPG5YYY5PP55GPJYYPGB########BBBGGGBGGBGPPP55PPGGPP                                               ",
    "                                        PPPPPG5GPPP5G#######BBBGBBBBBBBGGPP55PBBGGBBPPP5Y55GGPYJJ55Y?7                                  ?Y7             J5YJ?                                                        75P7?                                                                 YPPGGPPPPPPGBBBB#&#5PPGP55PGGG5YPPY5GBB#########BBBBGGBPPGGPGGPPPGB#BB                                               ",
    "                                       5PPPPGGPG5555B##BB#########BBBBBGGPP5YPGBGGBGPPPP55YY5P55Y5GBG5J                                ??JY               JPY                                                       765P                                                                JYPBBGGBGGBGGGPB#BGGB#&BPPGGGP5P55555JYGBB##########BGBBBBGGGBBBGGGBGGGGGG                                              ",
    "                                       GBGBBBGPP5PGPB###BB#########BBBBGGP5YJYPP5PGGGP5PPP5PPP555PGBBBP5YJ                               ?JJ              ??P5??                                                  ?75P7                                                             J5GB###BGGBBBBB##PBBBGGB##BGGGGGP5YY5JJY5PGBB########GGBBBBGGGGBBBPPPGG5GPPP                                                ",
    "                                       Y5PGBGBGGGGGGGBBBBBB######BBB###BBGG5JJYP55GPPYYY55555PPPPP5PGGPGPPPYJ                                                 PY?                                               ?77P57                                                           ?Y5GB####BBBBBBB####BGBB##&&#BP5PG5JJ5YJJJYPGBBBBB##BBBGPPGGGGPPGGGBBGPGGBGGGGP                                                ",
    "                                       ?YPPPPPP5BGP55GBBBBGBB#########B#BBBB5YY5GP55PP5YYY555P5G#BBBGPPPPPPGBPPYJ                                             ?5PJ??                                           ?7?P5                                                          JY5GGGBBBB##B####BB#####BBPB###BPY5PGPY55JJYY5PGGBBBBBBBGBGPPGGGGGBBBBBBBGB###B##                                                 ",
    "                                       JPPPP5PPPGP5PPGBBBBBBGBB####&&&#####BGPY5GGYPGGGP5555PPP&&BGB##GPGGPPGGPGBG5Y?                                           JPPJ                                           7JGP                                                         Y5PGPGBGGGGB#####B#####&#B#####BPGPGGBGP5PYJJY55PGBBB#BB#BBGGGBBBPPGGBBB##BBB#BBB#                                                  ",
    "                                       YBBGGBBBGP5PGGBBBBBBBBGBBBB###########BG55PP5PGGPPPPPPPB##BGBB#GB#BBBBGBBB###BP5                                           J5PY?                                       75P?                                                      JY5PGGGGGGBGGBB###########&&#######BPGGBBGPPP5555PPGBBB#BBBGGGGGPPGBBGGGBBBB#GGBBGGGGGG                                                 ",
    "                                       ?JPGBBBBGPGGGGGBBBBBBBBBBBB#####BBBBBBBBG5YY555PPP55PGB######BBPB&&######BBB####BP5J?                                        ?5PYJ                                   7?P                                                     ?J5GBBGGGB#GPGBB##########B###BG####BBBB###GGBGG5YY5PPPBBGGBBGGPPPPPPPGBBBPPGBBBBPPGG5GPP                                                   ",
    "                                       ???5PP55GPGGPPPGBBBBBBBBB#BGB###BBBBB#BGGP5JJJ5PYJYPPPPG#&&&#GBBB&&##B#####BBBBBBB#BP5YJ?                                      ?J55Y                                7YPJ                                                    YGB##BBBBBBBBBBBB######B##BBBB#BGBBBBB#####BGGBGP55Y55PGBBGGGGPPPPGPPGGGGGPPGGGGB#GGGBGG                                                     ",
    "                                       ???5P555PPPBPGPGBBBGGGGBBBBPGBBBBBBB#BGGGP5YJJYP5Y5GP5Y5PGG##B###&&#BBB########BGBBGBBBGP5J                                      7?Y55                            7JP577                                                 ?JYPP55555PPGGBBBBBBBBBBBBBBBBGBGBBB##############BGGGGGGBBBBBBGBGPPPGPPPGBGGBGGGGGGBBGGGPP                                                     ",
    "                                       ?YP5PPGBBBBBBBGB#BBBBGGBBBBGBBBBBBB###BBGPPYJJJYPP5PGBBGGYP&###BB#&&#############BBPPGBGGGGPP5Y?                                    ?JY55J                ?     775PJ7                                               JY5PGBGGGGGGP5PPPPGBBBBGGBBGGGGGBB################BBBBGGBB####BBPPPPP555P55PGP55PP55PPGGPPPPP                                                       ",
    "                                       ?5BGGGB######BBB##BGGGGGPBBBBBBGGBBBB##BBBGPG5YYYPGGGGBBBGP######BG###########B#####BBBBBB#B###BP5                                      J555J            ???   PYJG5                                               JYPPPPPGBGGPP555GGGGP5PPPPGPPPPPGB##################BGBBGGGGBBBBBGP5555PP5YY55PPPYY55555P5Y5PPP                                                       ",
    "                                        ?YGBBBB##BGBBBBB#BGGGBGPBBGGGPPPPGBBGGBBBGGGP55555GGGPG###BBB#B##BG##B##BBBBBBBBBB####BBGPPG5PPPGP5                                       JY5Y?       777JPJ? 5BGY                                            JYPPPPP55PGPP55P5P5PPPPPPG55P55YYG#&#################&#GGBBBGGGGGGP5555P5YY5P5YY555555JY555P5YPP                                                          ",
    "                                         ??YYGGGGGGGBBGPB##BBBGBBBBBGGGGPPPGPBBBBGBGPPP555GBGGGB#########BBBBGGGGGGBBBBBGGGGPGGBBBP55PPPPPPPPPP5J                                  ?JY55     JYYPG5JY#BGGP                                        PGBBGPPPPGGGP5PP5PPP5Y555PP55PPG#BY?JG#################BGGBGGGPPPGPPYYJYYYJY5Y5YY5YJJYY5Y555PGPP                                                              ",
    "                                          ???Y5555PPGGGPB#BBGGGGGGGBBGGGPPPP5GBBBBBBGBBGGGGGB#BB####B##########BGGPPPGGGPPGGPP5YY5GGGPPPPGP5P5PPPPYJ                                   ?J55 7P#GPBBG5GBGGGB                                    JYPB###BBGBBBGGGGGGGBPP55555Y55PPGGGBGPG57Y####&&&&&######GPBBBBGGBGGBBG555555YYY55PPPP5Y5GPPPPGGPG                                                              ",
    "                                          ??JPPP5PGGGPGGBBBBGGBBGGGGBBBGGPPPPPGBGB#BBBB#BGGPGB#BB#####B############BGGP555P5Y55Y5GBGPPPPP555PPP5PPPGGPPY                                ?7J5PPBGGBGBBBGPPGGGGP                               JYPPGBBBGBGGBBBBBGGBBBBBGGPP555YY5YYJYY5P55YJB&##GP5YP&&&##########B######BGGBBGGGGPGBBGPPGBBGPPPPP5                                                               ",  
    "                                             BBGPB#BGPPGGGGBGGGPPPG55GP55PYYYPPPPPPPPGBBGBGGPGBGP#&#################&B5YGPPGP55PPPP5YYY5GP55PGGGGGGGB###BGPYJ                            ?JYPBBGBGGGGGGGGGGPPGBBY                        JY5GBGGPGPPGGGGB##BPGB#BBBBP5PGB####BBBGP5YJ?7?7?YJJ???YB&&############BB###BBBBBBBBBBB#BGPGGGBBGGGG                                                                   ",
    "                                               PGGGGGPPPPP55PP5555555PP555YP5P55P555PPBGGBBGPGBBGB#&&#######&&###B##Y7YGB#BBG5Y55Y555P55YYPGGPGGGBBBBBBB####BG5YJ                       Y55PPGGGGGGGGGGGGGGGGGGGGYYYJ                J5PGGGPPBBGGPGBBB#####BPGBBBBGGGB##########&&&#BGP5YYYYY5PB#&####BBB####BBGG####BGGBBBBBBBBBP55PGGPP                                                                       ",
    "                                                  P55YP55P5JYGP5555555PP5PY555YJ555Y5PGPG#BGBGGBBBBBB#######&##&&###YJGBPPBGGPGP55555Y5PGGGGGGGGBB#BBBBBBGBBGGGGGP55J                 5PGBBBBBBBBGPGPY5PPPPPPPP55P5PP5P            YPGBB###BYBBPGBBB####BBB#BBB###BGG#############&&&&&&##&&&&&&######BBBBBBBGPBB####BGGBGGGGGGBBPYYY5P                                                                         ",
    "                                                   55YYP5G555PP5555PY5YY5P555PYYYY55PGPPB#B##BBB##BGGB######Y?JYGB##BJJYYJ???YPGB#&##BGG5PPPGGBBBGB#BBGBBGPGPPGBBBPPPPGPY         J5GB#&&&&#BBBGBBBB##B#######BBBBGBGGGP5        PPPPGGBB#B5BBGGBBBGBB##B#####BB##BB#############################BBBBBBGBBBBBBB#BBGB#GPGBGBBGGGG5PGP                                                                            ",
    "                                                     P5GPPPPPPPPG5PGGGPPPGGPGGPPPPPPPPGBBG###BBBGBBB########GY?!!!777!!~!?5B#&&&&&###&&&#BGBGGPGBPB####BGBGPPPGBBPB###BBBP5J    JPB#&###BGPPPP5PPGGGBBGGBPBBGGGGGPPPP5GPPPP    PGBBGGGPPGG5PGB#BBBBBB#########BBBBPB###BBBB#BBB###BB##############BBBBBBB#BBB####BGBBGGGBGGGGGGPPGP                                                                             ",
    "                                                       BGPPGPPPY55PPGPPPP5P5PBBGGGGGGGGBGGB##PPB#####B#########GP5YYJYY5G#&&##############B###B#BB###B#BB###BPPPBPYBBBBGGGBGG  YGGGGPPGY5GP55555555PPGBPGP5PGGP55PPPGPPPPPPGGP5GGGGGGBGPGGGB####B#####B###BBBGGGB#PYG####BGGGGGGGBBBBBBBBBBB#######BBBGGBBBBB####GBBGGBBBBBBBBBBBBG                                                                             ",
    "                                                           P5PP55PPPPPPPGPG5YG##BBBGGGGBBGB##BBGGBB#############&&&&&&#####################B###B#########BBBBBBBGGPPGBGPGGGBGBGPP5PPPPPP5P5PP55PPPPPPPGPPPP55GGPGGGGGPPGBBBGGPPGGGGGGBB######BBBB##BBBPP5PGBBGBB###55GB##BPPGGGGBBBBGGBBBBBBBBBBB###BBGGGGGB####GG#BGBBBBBBBBBB##B                                                                              ",
    "                                                             55PYYPP5555PPPP5PBBBBBBGGBGGG##BBBBGGBBBBBBBBBBBB##################BBBGBBGGBBBG5BBGBBB###&########BBBGGPGP5BGPPGGGPBGP5GGGGGGP5GP5P5PPPGPP555YP5PGGGGGGGGBBBBGGP5PPGBGPGBBB##&#PGBBBGGGPGGGPPPPGGGB##B5YGBGBGPPPGPPBBBBGGGGBBB#BBBBB##BBBBBBB#####G5###BBBBGGGPGBBBBB                                                                              ",
    "                                                                5JJJY55555YYYGGGPGGBGGBGGPGBGG###BBBBBBBBBBBBBBBBB##B##BBBBBBBBBGGGGBBB##G5YYB#BGPPPGBB#############BBBBGGGPGGBPGBBBBGGBGBBGP5GPGGP5P555YYJYPGBPGGGGG55PPGPPPGGBGGGBBBGG##BYYBBBBPBG5GGGPPPPPPGBBBPGBBBGG555PPPPGGBBBBBGBB####BBGBBPPPGBGGGBB##BY5B###GPGGGPBBBBBB                                                                              ",
    "                                                                  YYYPG5YY5Y5GPP55GBGGGBBPPBBGB##BBBBGBBGBGGBBBBBBBBBBBBBBBBGPGBPPPGPGB##B5YB###GGGG55PPPPGB#BBBBGG#&###BBGGBBGPGGBGGGBGBBBBGPPPPP5P5YYJJ5P5GPPGPGPPPPPP5555PPGG5PBBGP5PPG5YPGGGPPP5PP5PP5P55PGBGPGGBBBGBGGBBBBB#BB####BBBB##BBGGGBGGPPPPGGGBBB#G5PGGBBGGGGPGBBBBB                                                                              ",
    "                                                                    YPGP55G5PGBGPPGBBBBGBGPPBPG#BBGGGPPPPGGBBBB##BBBGGBGGGGBBPGGGPGGP5PB##55GB#BBGPGP555PP5PPG###B55BBBBBBBGGGGBBBPPPPGGGGBBBBBGPP555YYJY55G55GGGGGP5PPPP555PGGBGGGPPPPPGGGGGGGGGGGGGPPPPP55PPGGGGGBBBGGGBGGGGPG#BB#B##BBB##BBGGGGPGGGPPPGGP5YJJJ?????JJJJYY5PPB#BB                                                                             ",
    "                                                                        55G55GGB##BB##BBBGGGB#BG####BBBBBBBB#######BBGGGGGPPP55PPPPPPPPPG#BP5GBBPGGGG555P5Y5Y5PGGGG55GGPPPPGBPPGGPPPGGGGGGGBBBBBP5P5YYYYYY555PPGGGGGGPGGGPPPGBGGGGBGPGGBGBBBBBBBBBBBGPGGGGGGBGG######BBGGGGGBBGGBBBBBBBBBBBBB#BBBBGGPPP5PP555555555PP55555Y5555PGBBGP                                                                           ",
    "                                                                          5Y?YPBBBBGBBGGGGGBB#GJG##BGGBBGGGPGBBBBBGBBBGB#BBBBBBGGGGP5PPPGBBBBP5GGGP5P5P5555P55PPPGGGGPPPPPP5GGGGPPPPPGGGBBBBGBGGP5P5YY5555555PPGGGBGGPGPPPPPGGBGGGPPPPPGGGBBBBBBB##BBBB#BBGGGBBBBBBBBGBBBBBGBBBGGBGGGBGGGGGGPPP555YY55YY5YYYY55555PPPPPGGGGPPPPPPPPPP5                                                                          ",
    "                                                                            JYGBBBBBBBBGPGB##BY5B##BPPGGBGP5PGBGBGGB##BB##BGBBBGGGBGGPGBBB##BBGBBBBBBBBGGGGGGGGGGBBBBBBBGGGBBGGBGPPPGGGGBBB##GPPPP5YY55Y555PGPPPGBBGBB#GGGGGPGPPPPP5PGPGPGGBBBB#BBBGB#####BGG####BBGBBGGBBGPPGBGGGGPPPP55YYYYYYYYYYY5YYYYYY5555555PPPPPPGGGGGGGGGGGGGPGG                                                                        ",
    "                                                                            PGB#######BBBBBBBBBBBBBBGGGGGP5PGGBBBGB##BBBBBB#GGGBBBBGPPGGBBB######BB#&###BBBGGBBBBBBBBBBBGGPPPGGGGPPGGGBGGBBBGGGG555YP55PGGGBGGGGPGGGGGBB##BPPPPP555YYYY55PPGGGGGGGGGGB####GPB###BGGPGGGGGGGGPPGPGP5YYJYJJJJYYYYYYYYYYYY5YY555555PPPPGGGGGGPPP55PGGGBBGBBGG                                                                      ",
    "                                                                            GBB######BGPGPPPPPPP5PP5P5555PPGGPGGGGBBBGPGGBBGPGGGBPPPGGPGGGGBB#####BGB#####BGB#BBBBBBGPP5555555PP5PGBBPGGB#BGPP5Y55P55PPGBBBBGGGGGPGGGPPPGPPGP5PP55YJY5555555PPPPPPP5PPGGGPPPPPGBGGGPPP5555P5YYYY55YYYJYJYYYYYYYYYY55YYYY5555555555PPP5PPPPPPPPPGGGBGGGGBBP5                                                                     ",
    "                                                                         BBBB#####BBGGGGGPPPPP5PPP55YYYYYJJYYYYYYYY5P5PPPGGBGPGGPY5PGGPBBP5PGBBBB##G5P#&&#GGGGGGGBGPPP55YYYYYY55PPGBGGPGBGP5PP5Y5P5555PPBB######BBBBBBPPPP55P5PGGGPPPPPPPPGPPPGGGPYYPGGGGGGGGPPPPPPPP55P5PPGPPPPP5555YYYYYYYYYYYYYYYYYYYYYY555555PPPPPPPPPPPPPGGGGGGGBBBBBP5                                                                    ",
    "                                                                       PGGBBBBBBBGGGGGGGPPPPPPP5555555555555YYYYYY5Y55YY55555PGGGGBBBGBBGGGGBBBBB###GPGBBBBBBGGGGGGPP5PPPPP5P5YPGGGGPPGBGPPPPPPPPP5PGPPGB###BBBBBBBB##BGPPPP5PPGGPGGGGPP5555555555YYY5PPGGGGGGGGGGGGGGGGGGGGP55YY5555P5555YYJJJJJJJ??????JJY555PPPPPGGGGGGGGGGGGGGGGBBBBBBBBG                                                                   ",
    "                                                                      JY5GGGGGGGGGGGGGGGGGPPPPPPPPPP5555555YYY5YYYYYJYYYYYY555PPPPPGGBBBBBBGGGGGGBBGGPYJ5PPPPPGGGGGPP555555PPGGGGBGGGGGGP555PPPGPPPPGPPG#&&#############BBPPP5P5P5Y5PP55PPPPP555YYYYYJJYYYYYY55PP5PPPPPGGGGP5555YYYJYYYYY55PPPPPP55YYJJJ?JJYY5PPGGGGGGBBBBBBBBBBBBBBBBBBBBBBBG                                                                  ",
    "                                                                     JY5GGGGGGGGPPGGGGGGGGGGPPPPPP555YYJJJJJJJJJJJJJJYY55PPP555YYYYYYYPPGPPPP5P5555555555555YYYYYYYYYY55PPPPPPPPPBGGGGGPPPGGPP5GGGGPPPPB&&&&&&##BBB######BGGGPPPP55YY5555PPPPPPGPP5YYYYYYYJYYYJYYJYY555PGGP55555YYJJ????JJJYYY555PPGPPPP5PPPPPPPGGGGBBBBBBBBBBBBBBBBBB#BBBBBBGG                                                                 ",
    "                                                                     PPGGGBBBBGGGGGGGGGGGGGGPGPPPP5555YYJJJ?JJJY5PPPPPP5YYJJJJJJJJJ?JJY5PPPPPPP55P5555YYYJYYYYYYY55PPPPP5PPPPPPPPGGGGGBB####BB5PGGGGBGG#&&&&&##BBBB####BBBGGGGGPP5555Y555555PPPPPPP55YYYYJYYYYJYJJJJYYYYY55YYYJJJY5555555YYYYYJJJ?JYJJY55PPGGGBBGGGGBBBBBBBBBBBBBBBBBB#####G55                                                                  ",
    "                                                                     GBBBBBBBBBBBGGGGGGGGGGGGGPPPPP5555YY55Y5PPPP5YYJJJJ????JJJJJYYYY555PGP55YJJJJJYYYJY5YYYYY5PPPPPPPP55PPPPPPPPGGGGGBBB######GGBGBBBB#&&&&&&BBBPGGGGBBBBBBGGGPPPP555555555555PP5PPPP555YY555YYYJJJJJJJY5Y5YYYYJYYYYY5555PPPPP55PP5PP55PPPPPGGGGGGGBBBBBBBBBBBBBBB####BB#GYJ                                                                   ",
    "                                                                      BBBBBBBBGGGGGGGGBBGGGGGGGGGGPPGGGGGPP5YJJ??JJJJYYJJY5555YYYYJJ?JJJY5YJJJJJJJJJJYYYYYY5PPPGPPPPP555555555PPGPPPGGBBB#BBB##&##BBB###&&&&&&&##G55PGGBBBBBGGPP55PPPP5555YYY555PP555555555Y5PGGPP555YYY5YYYYYJ?7??????JJJJ??JJYY55PPPPPGBBBBB##BBBBBBBBBB##BBBBBBBBBBBBBBP5                                                                    ",
    "                                                                        BBBBBBBGGBBGBBBBBBBBBBBBBBBGGGP555YYYYYYYY5Y5Y5YYYYYYYJJJJJJJJYYYYYJJJYJJJYYY5PG555PPPPPPPP555555555P5PGP 55PGBBBBGGGB##&&&#####&&&&##BGG555PPGBBGGGGPP55YY5GGPP5PP5YYY555555PPPP555YY5555P5YYY5555555YYJJ?J???JJJJ????JJJY555PPPGGGGBBBBB#############B#BBBBBBBBBGGG                                                                   ",
    "                                                                        BBBBBBBBGGGBBBBBBBBBBBBGGGGPPGGGPGGPPPP55YYYYYYYYYYJYYJJJJJYYYYYYYYYYYYYYY5PPPPYY5PP5PPP555YYY55P5PPPPPY    55GBBGGGPGB##########&&##BBGPPP5PPPGGGGPP555YJYY55PP555PP5YYYY55555PPPPP555YYYYPPPYJ????JY5P55JJJJJYYYYYYJJJYYY555PPGGBBBBBBGBBBBBBB#BBBBBBB#BBBB##BGPPGPY                                                                  ",
    "                                                                        GBBBBBBGGGBBBBBBBBBBBBBBBBBBBBGGGGPPP555YYYJ???????7??????JJYY5555Y55YYY5PP5P5Y555555555555YY5P55P55PY       5PGGGGPPGBB############BGPPP55PPPPGPPPP55555YY 5Y5PP5Y5PP5P5YYYYY5555555555YYY5555P5J?????JJYYYJJJ?????JJJYY55555555PPGBBBBB#BBBBBBBBBBBBBBBBBBB#BPYYYY                                                                    ",
    "                                                                        GBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGGGPP555YJ????????JYYYYYYY55PP5YYYJJYY5PPP5YY5YY5Y55555YYYYY55PPP5Y5P          PPGGGP5PPB#########BBGPP555PPP55PPP555555555  5555PG5YYPP5P555YYYYY5555Y555555YYJJYYJ??7?????JYY555JJ?7??JJYY555PPPPGGGBBBBBBBB####BBBBBBBBBBBBB5JJ?                                                                      ",
    "                                                                        PPBBBBBBBBBBBBBBBBBBBBBBBBBBGGGGGP55555YYYYYYJJYY555YJYY555YJJJJ?JJ5PPYJJJYY5555555YYYYYY5YPGP55YP             PPPPP55PG##########BGGGGGGGP5Y5PPPPPG55PP      YYY555PP5YY555PPP5Y5YYY555555YY55555YY5555P5YJJJJJJJ?JJYY55PP555YY5PPGGGGGGGGGGGGGBBBBBBBBBBBBBPYJ                                                                        ",
    "                                                                         ???5BBBBBBBBBBBBBBBBBBGGGGBBBBGGGGGGPP55YYJ????J5PP5YJJJJJJJYYPPYYYJJYYYYYYY555YJYYYYYPGPP5YY5P5               ##5GGGGGGGGBBBB#BB#BGGGGGGGGBB##BBGPPP         JYY55PP5YYY5555PP55YYYYYY5555555555555555PP5YYJ?JJYYY55YY555555Y55PGGGGGGGGGGGGGGGGBBBBBBBBBBP                                                                           ",
    "                                                                          Y55BBBBBBBBBBBBBGGGGBBBBBBBBBGGGGPP5555YYY555P5YJJ?JJJJJJ5PP5YYYYYYYYYYY5555YJJYY55PP55YYYYPP5                ##5PGGGGBBBBBBBGGBBBBBBBBGGBBBBBPP5             Y555PGP5YYYYYYPP55YY5YYYYYYYYYYYYYY5555555555YJYYY55PPP55PPGGGPPPPPGGGGGGGGGBBBBBBGBBBBBBBBBB                                                                           ",
    "                                                                             YGBBBBBBBBBBBBBBBBBBBBBGGGPGPPGPPPPPPGGGPYJJJJJJJJJY5PP55YYYYYYYYY555YYJJJYY55PPPYYYJJ5PP5                 ##55PGGBBBBBBP5PPPGBBGGGGBGGGPP5                  Y555PGP5YYYYYY5555YJYYYYYYJJJJYY555PPPPPPPPPPGGG5PPPP55PGBBBBBBBGGGBGGGGGGGGBBBBBBBBBBBGPPP                                                                           ",
    "                                                                             ??PBBBBBBBBBBBBBBBGGGGGGGGGGGGGPGGBGGG5555YYJJJJJJ5PP55Y55Y555Y555YYJJJYYY5P5PP55YYYY5PPP                  ####PPGBBBBBG5Y5PPPPGGGGGBGGGP5                    YYY55PGP5YYYYYY555YJYYYY55YYYYYY5555PPPGGGGGGGGBGGGGP555GBBBBBBBBBBBBGBBGGGGGBBBBBBBGYJYYY                                                                           ",
    "                                                                              5GBGBBBBBBBBBGGGGGGGGGGGGBBBBBBBGGPP5PPP555555PPP5YYYY55555Y5555YYJJYYYY55P5555YYYY5PPP                   ##P##PGGGGGGGGP5PP5PGPPPGGGGGPY                     YYY55PGGPYYYYY55555YYYYY555YYYYY55P55PPPGGGBGGGBBBBGGG55PGBBBBBBBBBBBBBBBBBBBGGGBBBYJYJ                                                                             ",
    "                                                                                BBBBBBBBBBBBBBGGGGBBBBBBBBBBGPPPPPPGPPPPPPGGPP55555YYYYY555YYYYYJYYYY55555YYYYY5PPPP                     ##BPPGGBBBBGGGGP5PGGGPGPPGGG5Y                     YYY555PGP5YY555Y5555YYYY5555YYYJY55PPPPGGGGBBBBGGGBBBBBGGBBGBBBBBBBBBBBBBBBBBBBBBGPG                                                                                ",
    "                                                                                 5PBBBBBBBBBBBGGGGBBBBBBBBGGGGGGGGGGPGGGGGGGPPPPPP55555555YYYYYYYYY5555555YYYY5PP5P                       ####B##BBBBGGGGP5555GPPPGGGP                        YYY555PGGPYY555YY555P55555555YY5YYY5PGGGGBBBGGGPPGB###BBBBBBBGBBBBBBBBBBBBBBBGGGG                                                                                 ",
    "                                                                                  ??PBBBBBBBBGBBBBBGGGGGGGBBBBGGGGPGBBBBGGGGGGGPPPPP5YYYY55555YYYY555555YYYY55PPPPP5                     ##B5PGBBBBBGGGGGGP555PPGBBGP5                         JYY555PPGPYY555YY55PPP55555PP5Y555Y5PPGGGGGGGBBBBB#######BBBBBBBBBBBBBBBBPYYY                                                                                    ",
    "                                                                                  Y5YGBGGGBBBBBBBGBBBBBBBGGGGGGGBBBBBBBBGGGGGGGGPPP5YYYYY5555YY55P55555YYY555PP55P5Y                    ##B55PGGBBBGBBBBBGP5555GGGGGP                           JY5555PPPP5Y5555555PPPP5555555555P5PP5PGGPGGBBBBBBB#####BBB###BBBBBBBBG5YJ                                                                                      ",
    "                                                                                    PGGBBBBBBBBBBBBBGGGGGGGGGBBBBBBBBBBBBGGGGGBG555YYYY555555555555555YYYP55PPP555Y                      JYY5PPGBBBBBBGGGBPPY5PGPGPPP55                          JYY555PPPP55P5555555PPPP555555P5PPPPGPPP55PGGBBBBBBBBB############BBGGP                                                                                        ",
    "                                                                                     GGGGGGBBBBBGBBGGGGGGGGBBBBBBBBBBBBBBBBGGPP555YYYY555Y55PP5555555YY5PPPPPP555YY                     JY5Y5PPGGBBGGPPGPPPPY5PGPPP55P55                           YY555PPPPP5P5555555P55PP55Y55PPPPPGGGGP55PGGBBBBBBBBBBBBB##BBBGGGBG                                                                                          ",
    "                                                                                          JJYPBBBGGGGBBBBBBBBBBBBBBBBBBBBBBGPPPP55555P5555PPP55555555Y5PP5PPP55YY                     JY5PP5PPPPGGPPPPPBGPPP55PGP555555G                            YYYY5PP55P5PPP55555P55PPP5555PPGGGGGGGGPPPGGBBBBBBBGGBBBG55Y5555                                                                                            ",
    "                                                                                           ?YYPGBBBBBBBBBBBBBBBBBBBBBBBBBBPPGGP5PPPPP55555P55555555555PPPPPP5YYY                      JJY5PGP5PPGGGGGGGBBG5PPPGBPPY555Y5G                            JJYY55P5555PPPPPP55PPPPPPPPP5PPGGGGBBBBBGGGPGBBBBBBGG5YYYYJJJJ                                                                                             ",
    "                                                                                               BBBBBBBBBBBBBBBBBBBBBBBBBGPGGGGPPPPPPPPPPPP5555Y555555P5PPP555Y                        JJYPGGYPPGGBBBBGBB#BGGPPGBGBGGP55Y                               JYYY55PP55PPPPPP5PPPPPPGGGPPPPGGGGGGBBBBBGPPGBBGPYJYJJ???                                                                                                ",
    "                                                                                                  5YY55PPGGBBBBGGBBBBGGGGGBGGGPGGGGGPGGPP5555555PP55PPPP555YY                         JY5PPPY5PPGBGGBBBBBBGGPPPPPPP5PPP                                  JYYY55PP5PPPPPPPPPPPGGGGGGGPPGGPGGGGGGBBBGGP5YYYJ???                                                                                                   ",
    "                                                                                                     JYYYYYYPGBBBBBGGGBGGBGGGGGGGGPGGGGPPP5555PPPP55PPP55YYY                          JY5PPP555PGGGGBBBBGGGGPPPG555555P55                                  YYYY5P5PPPPGPPPPPPPGGP5GGGGGGGGGGGGGGGGP5YYJJJ??                                                                                                     ",
    "                                                                                                           JYY55PGGGGGGGGGGBGGGGGGGGGGPPP55PPPPPP555PP55YJ                           JJJJ5PPP5PPPGGGBBBBGBBPGGGBPP5Y55Y5                                     YYY555PPPPPPPPPPPGGGGGGGGGGGGGGGGGGP5YYJJ????                                                                                                      ",
    "                                                                                                            JJJJYYPGBGGGGGGBBBBBGGBGGPPPPPPPPPPPP5PPP5YY                              JJJYPGGPGBPBBB#######BB#BBG5PP5PP                                        YYYYY5PPPPGPPPPPPPGGPPGPGPP5PP55555J?777?                                                                                                        ",
    "                                                                                                               ?JY55PGGGGGGGGGBGGGGGGPPPPPPPPPPP55555YY                               JJJYPGGGBBBBBBB###########BGPGPP5                                          YYYY55PPPPPPPP55PPP55PP5P5YYYJJJJ??                                                                                                            ",
    "                                                                                                                  JY5PGPPPPGPPGPPGPPPPPPPPP55PPPP55YYY                               JJJYPPPB#BGGGBGGBBB###B#####BBBGPY                                             JYYY55PPPPP5YY555YJYJYYYJJJJ?                                                                                                               ",
    "                                                                                                                  ?JY555555PPPPPPP55P5PPPP55555555YY                                 JJJ55PGBBGGGGGGGBBB##BBBB####BBGGPY                                             JJYYYY55555YYYYYYJJJJJJJ                                                                                                                   ",
    "                                                                                                                       JJYYYYYY5YYY555555YYY555Y                                         Y5GGBPGGGGBBB###BBBBBBBBGBBBPP                                                  YYYYYYYYYYYYYYYJJJ                                                                                                                     ",
    "                                                                                                                                                                                        YJJJJJJJYPGBGGGGGGB##BBB##BBB                                                                                                                                                                                           ",
    "                                                                                                                                                                                          JJJJJJJJYYYJJJJJJJYPGBBGGG                                                                                                                                                                                            ",
    "                                                                                                                                                                                           JJYYYYJJJJJYPPBBGGGBBB#                                                                                                                                                                                              ",
    "                                                                                                                                                                                            GBBGGGBB####BBBBBBBBBBG                                                                                                                                                                                             ",
    "                                                                                                                                                                                           PGBBBGBB######BBBBBB#BBGG                                                                                                                                                                                            ",
    "                                                                                                                                                                                           5GBBBBBBBBBBBB#BBBB###Y                                                                                                                                                                                              ",
    "                                                                                                                                                                                           YGGBBBBGGGBBBBBBBBB###                                                                                                                                                                                               ",
    "                                                                                                                                                                                           YPBBBBBGPGGBGGBBBBBBBBBG                                                                                                                                                                                             ",
    "                                                                                                                                                                                            YY5GGGPGGGBBBBBBBB###                                                                                                                                                                                               ",
    "                                                                                                                                                                                             55Y5YPBB#####BBBBG                                                                                                                                                                                                 ",
    "                                                                                                                                                                                              YYYG##GG###BGP                                                                                                                                                                                                    ",
    "                                                                                                                                                                                               YY5BGG5YPPBB                                                                                                                                                                                                     ",
    "                                                                                                                                                                                                YY55YYYY                                                                                                                                                                                                        ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                ",
    "                                                                                                                                                                                                                                                                                                                                                                                                                "
]

# Parámetros para mejor visibilidad
fig, ax = plt.subplots(figsize=(30, 20), dpi=300)
ax.set_facecolor('black')
plt.axis('off')


# Pintar cada carácter en coordenadas fijas
for y, line in enumerate(ascii_moth):
    for x, char in enumerate(line):
        if char.strip():
            ax.text(x*1.0, # Espaciado horizontal
                    -y*1.0 # Espaciado vertical
                    , char, fontsize=4, color='#00FF00',  family='monospace', 
                ha='center',
                va='center')

# Ajustar límites del gráfico para que todo se vea bien
ax.set_xlim(-1, max(len(line) for line in ascii_moth))
ax.set_ylim(-len(ascii_moth) - 1, 1)

plt.subplots_adjust(left=0, right=1, top=1, bottom=0)
# Guardar imagen sin recorte
plt.savefig("ascii_moth_clean.png", dpi=300, facecolor='black', bbox_inches='tight', pad_inches=0)
plt.close()