"""
Django settings for tuffsite project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carpeta base para los archivos subidos (imagenes, vídeos, etc.).
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Nombre de la vista de login (para el decorador @login_required o redirecciones automáticas)
LOGIN_URL = 'accounts:login'

# Página a la que ir tras un login exitoso (aún no existe, la crearemos luego)
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gcof&%s9#3(jrs66q-6)zff&k2!m+hw532w_kt%j5!b*&7*zf7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

     # Aplicaciones de terceros
    'widget_tweaks',  # Para modificar atributos de widgets en plantillas

    'accounts',  # Nuestra app de cuentas
    'dashboard',  # Nuestra app de dashboard
    'recognition_face',  # Nuestra app de reconocimiento facial
    'recognition_plate', # Nuestra app de reconocimiento de matrículas
    'personas.apps.PersonasConfig', # Configuración de la app Personas
    'matriculas', # Nuestra app de matrículas
    'utilidades',  # Nuestra app de utilidades
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tuffsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tuffsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'tuff9_db',
        'USER': 'tuff9_user',
        'PASSWORD': '1234',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL del broker: redis://<HOST>:<PUERTO>/<DB_index>
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_TASK_ACKS_LATE = True
CELERYD_PREFETCH_MULTIPLIER = 1
CELERYD_CONCURRENCY = 8  # Ocho si hay más núcleos/GPU
CELERYD_POOL = 'prefork'

CELERY_TASK_ROUTES = {
     # Matrículas
    'recognition_plate.tasks_plate.process_image_plate': {'queue': 'imagenes'},
    'recognition_plate.tasks_plate.process_video_plate': {'queue': 'videos'},

    # Rostros
    'recognition_face.tasks.procesar_imagenes_task': {'queue': 'face_imagenes'},
    'recognition_face.tasks.procesar_video_task': {'queue': 'face_videos'},

    # Utilidades
    'utilidades.tasks.generar_reporte_task': {'queue': 'utilidades'},
    'utilidades.tasks.bulk_check_task':    {'queue': 'utilidades'},
}


# Opcionales: formato de serialización
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Zona horaria de Celery (coincide con Django)
CELERY_TIMEZONE = 'Europe/Madrid'

PLATE_RECOGNIZER_TOKEN="" # Aqui va la api

OCR_API_URL="https://api.platerecognizer.com/v1/plate-reader/"
