# Generated by Django 5.2.1 on 2025-06-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personas', '0003_centroidepersona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Ej: 1234ABC (sin guiones ni espacios, siempre en mayúsculas)', max_length=15, unique=True)),
                ('esta_robado', models.BooleanField(default=False, verbose_name='¿Vehículo robado?')),
                ('delitos', models.TextField(blank=True, help_text='Lista de delitos asociados (opcional)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez_vista', models.DateTimeField(blank=True, null=True)),
                ('propietarios', models.ManyToManyField(blank=True, related_name='vehiculos', to='personas.persona')),
            ],
        ),
    ]
