# Generated by Django 5.2.1 on 2025-06-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='pais',
            field=models.CharField(blank=True, help_text='Código del país de la matrícula (ej. ES, FR...)', max_length=10),
        ),
    ]
