# Generated by Django 5.2.1 on 2025-06-09 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('matricula', 'Matrícula'), ('persona', 'Persona')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('input_file', models.FileField(upload_to='checks/%Y/%m/%d/')),
                ('result_file', models.FileField(blank=True, upload_to='checks/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('summary', 'Resumen búsquedas'), ('stats', 'Estadísticas')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='reports/%Y/%m/%d/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('plate_video', 'Placa Vídeo'), ('plate_image', 'Placa Imagen'), ('face_video', 'Rostro Vídeo'), ('face_image', 'Rostro Imagen')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('params', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
