# Generated by Django 5.2.1 on 2025-06-02 21:39

import django.db.models.deletion
import personas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('dni', models.CharField(max_length=15, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
                ('en_busca_captura', models.BooleanField(default=False, verbose_name='¿En busca y captura?')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('foto_principal', models.ImageField(blank=True, help_text='Sube la foto principal de esta persona (JPEG/PNG).', null=True, upload_to=personas.models.ruta_foto_principal)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialPenal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delito', models.TextField()),
                ('fecha_delito', models.DateField()),
                ('lugar', models.CharField(max_length=100)),
                ('sentencia', models.TextField()),
                ('estado', models.CharField(choices=[('cumplida', 'Cumplida'), ('pendiente', 'Pendiente'), ('absuelto', 'Absuelto')], max_length=50)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes', to='personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('tipo', models.CharField(choices=[('actual', 'Actual'), ('anterior', 'Anterior'), ('otra', 'Otra')], max_length=20)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='personas.persona')),
            ],
        ),
        migrations.CreateModel(
            name='EmbeddingPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='personas.persona')),
            ],
            options={
                'verbose_name': 'Embedding de Persona',
                'verbose_name_plural': 'Embeddings de Personas',
                'unique_together': {('persona', 'fecha_creacion')},
            },
        ),
    ]
