# Generated by Django 5.2.1 on 2025-06-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embeddingpersona',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, help_text='SHA256 del fichero original para detectar duplicados exactos.', max_length=64, null=True),
        ),
    ]
