# Generated by Django 5.2.1 on 2025-06-06 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_embeddingpersona_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroidePersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_promedio', models.JSONField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='centroide', to='personas.persona')),
            ],
        ),
    ]
